name: m183_lb2_node
include:
  - ../docker/compose.db.yaml
services:
  web:
      image: node:latest
      user: "node"
      working_dir: /home/node/app
      container_name: m183-lb2-web
      environment:
        - DBSERVER=m183-lb2-db
        - NODE_ENV=production
      ports:
        - "80:3000"
      volumes:
        - type: bind
          source: ../todo-list-node
          target: /home/node/app
      command: sh -c "sleep 10 && npm start"